<?php
// NOWDOC идеально подходит для шаблонов с синтаксисом, похожим на PHP
$data = [
    'title' => 'Configuration File',
    'settings' => [
        'debug' => true,
        'cache' => 3600,
        'db_host' => 'localhost'
    ]
];

echo <<<'CONFIG'
; <?php /* DO NOT EDIT THIS FILE DIRECTLY */ ?>
; Auto-generated configuration file

[application]
title = "$data['title']"
version = "1.0.0"

[settings]
debug = $data['settings']['debug']
cache = $data['settings']['cache']
db_host = "$data['settings']['db_host']"

; This is a comment
; All $variables are treated as literal text

CONFIG;

echo "\n---\n";

// А вот с HEREDOC переменные интерполируются
echo <<<CONFIG
; Dynamic configuration file
; Generated on: <?php echo date('Y-m-d'); ?>

[application]
title = "{$data['title']}"
version = "1.0.0"

[settings]
debug = {$data['settings']['debug']}
cache = {$data['settings']['cache']}
db_host = "{$data['settings']['db_host']}"

CONFIG;
?>